-- MySQL Script generated by MySQL Workbench
-- Mon May 20 18:24:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dw_ufgd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dw_ufgd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dw_ufgd` DEFAULT CHARACTER SET latin1 ;
USE `dw_ufgd` ;

-- -----------------------------------------------------
-- Table `dw_ufgd`.`Dimensao_Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_ufgd`.`Dimensao_Disciplina` (
  `chave_disciplina` INT NOT NULL,
  `nome_disciplina` VARCHAR(100) NULL,
  PRIMARY KEY (`chave_disciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_ufgd`.`Dimensao_Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_ufgd`.`Dimensao_Curso` (
  `chave_curso` INT NOT NULL,
  `curso` VARCHAR(100) NULL,
  PRIMARY KEY (`chave_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_ufgd`.`Dimensao_Academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_ufgd`.`Dimensao_Academico` (
  `chave_academico` INT NOT NULL,
  `academico` VARCHAR(100) NULL,
  `sexo` VARCHAR(100) NULL,
  `ano_ingresso` INT NULL,
  `bolsa` VARCHAR(100) NULL,
  `filhos` VARCHAR(100) NULL,
  `trabalha` VARCHAR(100) NULL,
  `turno` VARCHAR(100) NULL,
  `raca` VARCHAR(100) NULL,
  `maior_25` VARCHAR(100) NULL,
  `estado_final` VARCHAR(100) NULL,
  PRIMARY KEY (`chave_academico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_ufgd`.`Dimensao_Historico_Academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_ufgd`.`Dimensao_Historico_Academico` (
  `chave_historico_academico` INT NOT NULL,
  `academico` VARCHAR(100) NULL,
  `disciplina` VARCHAR(100) NULL,
  `nota` DECIMAL(4,2) NULL,
  `faltas` INT NULL,
  `resultado` VARCHAR(100) NULL,
  PRIMARY KEY (`chave_historico_academico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_ufgd`.`Dimensao_Tempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_ufgd`.`Dimensao_Tempo` (
  `chave_tempo` INT NOT NULL,
  `semestre` CHAR(10) NULL,
  `ano` INT NULL,
  PRIMARY KEY (`chave_tempo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_ufgd`.`Dimensao_Geografia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_ufgd`.`Dimensao_Geografia` (
  `chave_geografia` INT NOT NULL,
  `cidade` VARCHAR(100) NULL,
  `estado` VARCHAR(100) NULL,
  PRIMARY KEY (`chave_geografia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dw_ufgd`.`Fato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dw_ufgd`.`Fato` (
  `chave_curso` INT NOT NULL,
  `chave_academico` INT NOT NULL,
  `chave_disciplina` INT NOT NULL,
  `chave_historico_academico` INT NOT NULL,
  `chave_tempo` INT NOT NULL,
  `chave_geografia` INT NOT NULL,
  `media_aproveitamento` DECIMAL(4,2) NULL,
  `numero_evasao` INT NULL,
  `numero_academicos_regulares` INT NULL,
  `numero_diplomados` INT NULL,
  INDEX `fk_Fato_Dimensão_Geografia_idx` (`chave_disciplina` ASC) VISIBLE,
  PRIMARY KEY (`chave_curso`, `chave_academico`, `chave_disciplina`, `chave_historico_academico`, `chave_tempo`, `chave_geografia`),
  INDEX `fk_Fato_Dimensao_Curso1_idx` (`chave_curso` ASC) VISIBLE,
  INDEX `fk_Fato_Dimensao_Academico1_idx` (`chave_academico` ASC) VISIBLE,
  INDEX `fk_Fato_Dimensao_HISTORICO_ESCOLAR1_idx` (`chave_historico_academico` ASC) VISIBLE,
  INDEX `fk_Fato_Dimensao_Tempo1_idx` (`chave_tempo` ASC) VISIBLE,
  INDEX `fk_Fato_Dimensao_Geografia1_idx` (`chave_geografia` ASC) VISIBLE,
  CONSTRAINT `fk_Fato_Dimensão_Geografia`
    FOREIGN KEY (`chave_disciplina`)
    REFERENCES `dw_ufgd`.`Dimensao_Disciplina` (`chave_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_Dimensao_Curso1`
    FOREIGN KEY (`chave_curso`)
    REFERENCES `dw_ufgd`.`Dimensao_Curso` (`chave_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_Dimensao_Academico1`
    FOREIGN KEY (`chave_academico`)
    REFERENCES `dw_ufgd`.`Dimensao_Academico` (`chave_academico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_Dimensao_HISTORICO_ESCOLAR1`
    FOREIGN KEY (`chave_historico_academico`)
    REFERENCES `dw_ufgd`.`Dimensao_Historico_Academico` (`chave_historico_academico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_Dimensao_Tempo1`
    FOREIGN KEY (`chave_tempo`)
    REFERENCES `dw_ufgd`.`Dimensao_Tempo` (`chave_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fato_Dimensao_Geografia1`
    FOREIGN KEY (`chave_geografia`)
    REFERENCES `dw_ufgd`.`Dimensao_Geografia` (`chave_geografia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
